table fact_deudores
	isHidden
	lineageTag: 1f5fd0e2-642b-58fe-95e2-76ca0143f739

	column fecha
		dataType: dateTime
		formatString: yyyy-mm-dd
		isHidden
		lineageTag: 093987c5-676d-548f-886a-6c0da1cbf658
		summarizeBy: none
		sourceColumn: fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column entidad_id
		dataType: string
		isHidden
		lineageTag: e71ee025-4766-5ef0-b6b6-e93ca0791dd4
		summarizeBy: none
		sourceColumn: entidad_id

		annotation SummarizationSetBy = Automatic

	column tipo_credito
		dataType: string
		isHidden
		lineageTag: 922f2804-6cd5-5414-8ffc-dae980b55e12
		summarizeBy: none
		sourceColumn: tipo_credito

		annotation SummarizationSetBy = Automatic

	column deudores
		dataType: double
		formatString: #,##0.00
		lineageTag: 3e3e91e0-4387-5d07-87da-de8c566c8bf5
		summarizeBy: sum
		sourceColumn: deudores

		annotation SummarizationSetBy = Automatic

	partition fact_deudores = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents(RutaDatos & "fact_deudores.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Encabezados = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    Tipos = Table.TransformColumnTypes(Encabezados, {{"fecha", type date}, {"entidad_id", type text}, {"tipo_credito", type text}, {"deudores", type number}}, "en-US")
				in
				    Tipos

	annotation PBI_ResultType = Table
